openapi: 3.2.0
info:
  title: ONESOURCE Income Tax Charts Schedule M3 Line Mapping API
  description: 'Charts are used to identify Tax Return Code (TRC) and Tax Combination Code (TCC) accounts and adjustments for multiple entities and binders. Use REST APIs to automatically manipulate basic chart functions.


    The charts are related by using elements from other charts to create a set of charts. Each set of charts is then assigned to an entity to use for TRC/TCCs, accounts, and adjustments. Chart assignments are either Common or Separate.'
  termsOfService: ''
  version: v1
servers:
- url: https://api.onesourcetax.com/income-tax/charts
security:
- Authorization: []
tags:
- name: Schedule M3 Line Mapping
paths:
  /v1/years/{year}/tax-return-types/{taxReturnType}/fcoa/{fcoaChartId}/charts/schedule-m3-chart/unmapped-accounts:
    get:
      tags:
      - Schedule M3 Line Mapping
      summary: Returns a list of unmapped accounts for the Schedule M3 Chart.
      operationId: RetrievesUnmappedAccountsList
      parameters:
      - name: year
        in: path
        required: true
        schema:
          type: string
      - name: taxReturnType
        in: path
        required: true
        schema:
          type: string
      - name: fcoaChartId
        in: path
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        description: Indicates the response content media type to return. application/json is currently the only option.
        required: true
        schema:
          type: string
          default: application/json
          enum:
          - application/json
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleM3LineMappingMappedAccountsRepresentaion'
        '401':
          description: Indicates a lack of authorization to perform this action on this resource. Check credentials and rights.
          content: {}
        '404':
          description: Not found.
          content: {}
        '500':
          description: Unexpected error encountered. Contact ONESOURCE Technical Support.
          content: {}
      deprecated: false
      x-operation-id-source: normalized
      x-operation-id-original: Retrieves Unmapped Accounts List
  /v1/years/{year}/tax-return-types/{taxReturnType}/fcoa/{fcoaChartId}/charts/schedule-m3-chart/mapped-accounts:
    get:
      tags:
      - Schedule M3 Line Mapping
      summary: Returns a list of mapped accounts for a Schedule M3 Chart.
      operationId: RetrievesMappedAccountsList
      parameters:
      - name: year
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: taxReturnType
        in: path
        required: true
        schema:
          type: string
      - name: fcoaChartId
        in: path
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        description: Indicates the response content media type to return. application/json is currently the only option.
        required: true
        schema:
          type: string
          default: application/json
          enum:
          - application/json
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleM3LineMappingLineAccountRepresentaion'
        '401':
          description: Indicates a lack of authorization to perform this action on this resource. Check credentials and rights.
          content: {}
        '404':
          description: Not found.
          content: {}
        '500':
          description: Unexpected error encountered. Contact ONESOURCE Technical Support.
          content: {}
      deprecated: false
      x-operation-id-source: normalized
      x-operation-id-original: Retrieves Mapped Accounts List
    patch:
      tags:
      - Schedule M3 Line Mapping
      summary: Maps or unmaps the accounts for Schedule M3 Chart
      operationId: MapsAndUnmapsAccounts
      parameters:
      - name: year
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: taxReturnType
        in: path
        required: true
        schema:
          type: string
      - name: fcoaChartId
        in: path
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        description: Indicates the response content media type to return. application/json is currently the only option.
        required: true
        schema:
          type: string
          default: application/json
          enum:
          - application/json
      - name: Content-Type
        in: header
        description: Indicates the response content media type to return.
        required: true
        schema:
          type: string
          default: application/json
          enum:
          - application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JsonPatchDocumentScheduleM3LineMappingMappedAccountRepresentaion'
            examples:
              M3-Add_Account:
                $ref: '#/components/examples/M3-Add_Account'
              M3-Add_Account_Simplified:
                $ref: '#/components/examples/M3-Add_Account_Simplified'
              M3-Remove_Account:
                $ref: '#/components/examples/M3-Remove_Account'
              M3-Remove_Account_Simplified:
                $ref: '#/components/examples/M3-Remove_Account_Simplified'
        required: true
      responses:
        '200':
          description: Success.
          content: {}
        '400':
          description: Request failed. This is usually due to validation errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemRepresentation'
        '401':
          description: Indicates a lack of authorization to perform this action on this resource. Check credentials and rights.
          content: {}
        '404':
          description: Not found.
          content: {}
        '500':
          description: Unexpected error occurred. Contact ONESOURCE Technical Support.
          content: {}
      deprecated: false
      x-codegen-request-body-name: lineCodeswithMappedAccountPatchDocument
      x-operation-id-source: normalized
      x-operation-id-original: Maps and unmaps Accounts
components:
  schemas:
    ProblemRepresentation:
      type: object
      properties:
        type:
          type: object
          format: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
        fieldErrors:
          type: array
          items:
            $ref: '#/components/schemas/FieldError'
    FieldError:
      type: object
      properties:
        fieldName:
          type: string
        messages:
          type: array
          items:
            type: string
        errorCode:
          type: integer
          format: int32
    ScheduleM3LineMappingMappedAccountRepresentaion:
      type: object
      properties:
        id:
          type: integer
          format: int32
        parentId:
          type: integer
          format: int32
        detailLineId:
          type: integer
          format: int32
        hasBalance:
          type: boolean
        accountId:
          type: integer
          description: System-generated ID for an account number in the chart of accounts.
          format: int32
        accountCode:
          type: string
          description: Account number in the chart of accounts.
        accountDescription:
          type: string
          description: Account description in the chart of accounts.
        accountType:
          type: string
          description: Account code associated with either income or balance sheet (mutually exclusive).
        tccId:
          type: integer
          description: System-generated ID code used to combine accounts into subcategories within a single TRC (Tax Return Code).
          format: int32
        trcCategoryId:
          type: integer
          description: System-generated ID for TRC.
          format: int32
        trcNumber:
          type: integer
          description: System-defined number for a TRC.
          format: int32
        trcDescription:
          type: string
          description: System-defined description for a TRC.
        tccNumber:
          type: string
          description: User-defined code used to combine accounts into subcategories within a single TRC.
        tccDescription:
          type: string
          description: System-defined description for a TRC.
        trcFormattedNumber:
          type: string
          description: System-defined number for a TRC.
    ResponseRepresentation:
      type: object
      properties:
        httpStatusCode:
          type: integer
          format: int32
        detail:
          type: string
        fieldErrors:
          type: array
          items:
            $ref: '#/components/schemas/FieldError'
    OperationScheduleM3LineMappingMappedAccountRepresentaion:
      type: object
      properties:
        value:
          $ref: '#/components/schemas/ScheduleM3LineMappingLineAccountRepresentaion'
        path:
          type: string
        op:
          type: string
        from:
          type: string
    LineCodeRepresentation:
      type: object
      properties:
        year:
          type: integer
          description: Tax year.
          format: int32
        taxReturnType:
          type: string
          description: IRS-defined type of tax return.
        id:
          type: integer
          format: int32
        formPartId:
          type: integer
          format: int32
        parentId:
          type: integer
          format: int32
        description:
          type: string
        code:
          type: string
        lineNumber:
          type: string
        detailLineId:
          type: integer
          format: int32
        detailType:
          type: string
        isCodeAssigned:
          type: boolean
        subLineCodeList:
          type: array
          items:
            $ref: '#/components/schemas/LineCodeRepresentation'
        detailLineList:
          type: array
          description: User-defined Schedule M3 detail.
          items:
            $ref: '#/components/schemas/LineCodeRepresentation'
        mappedAccounts:
          type: array
          items:
            $ref: '#/components/schemas/ScheduleM3LineMappingMappedAccountRepresentaion'
        response:
          $ref: '#/components/schemas/ResponseRepresentation'
        rowNumber:
          type: integer
          format: int32
    JsonPatchDocumentScheduleM3LineMappingMappedAccountRepresentaion:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/OperationScheduleM3LineMappingMappedAccountRepresentaion'
    FormPartRepresentation:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
        lineCodeList:
          type: array
          items:
            $ref: '#/components/schemas/LineCodeRepresentation'
    ScheduleM3LineMappingLineAccountRepresentaion:
      type: object
      properties:
        year:
          type: integer
          description: Tax year.
          format: int32
        taxReturnType:
          type: string
          description: IRS-defined type of tax return.
        chartId:
          type: string
          description: System-generated unique identifier for a chart.
        displayTaxReturnType:
          type: string
          description: Tax return type description.
        canDoRollover:
          type: boolean
          description: Indicates whether a chart is available for rollover.
        isRolloverDone:
          type: boolean
        isRolloverEnabled:
          type: boolean
        formPartList:
          type: array
          items:
            $ref: '#/components/schemas/FormPartRepresentation'
    ScheduleM3LineMappingMappedAccountsRepresentaion:
      type: object
      properties:
        resourceList:
          type: array
          items:
            $ref: '#/components/schemas/ScheduleM3LineMappingMappedAccountRepresentaion'
  examples:
    M3-Remove_Account:
      value:
      - path: /federalAccounts
        op: remove
        value:
          accountId: 2111111118
          accountCode: '303000'
          accountDescription: 'Sch K: Dividend Income'
          accountType: Balance Sheet
          tccId: 1
          trcCategoryId: 10
          trcNumber: 100
          trcDescription: Cash
          tccNumber: '001'
          tccDescription: Cash1
          trcFormattedNumber: 10-100
          Id: 3
          detailLineId: 1234
    M3-Add_Account:
      value:
      - path: /federalAccounts
        op: add
        value:
          accountId: 2111111118
          accountCode: '303000'
          accountDescription: 'Sch K: Dividend Income'
          accountType: Balance Sheet
          tccId: 1
          trcCategoryId: 10
          trcNumber: 100
          trcDescription: Cash
          tccNumber: '001'
          tccDescription: Cash1
          trcFormattedNumber: 10-100
          Id: 3
          detailLineId: 1234
    M3-Remove_Account_Simplified:
      value:
      - path: /federalAccounts
        op: remove
        value:
          accountId: 2111111118
          Id: 3
          detailLineId: 1234
    M3-Add_Account_Simplified:
      value:
      - path: /federalAccounts
        op: add
        value:
          accountId: 2111111118
          Id: 3
          detailLineId: 1234
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
