# x-archived-from: thomson-reuters-next-generation-reporting-rest-apis-openapi.yml
# x-archived-on: 2026-10-20
openapi: 3.0.1
info:
  title: Next Generation Reporting REST APIs
  description: Transaction Extract Reporting REST APIs enable you to access transaction-level data for selected companies according to the unique needs of your organization.
  contact:
    name: IDTAWSResourceOwners@thomson.com
    email: IDT AWS Support
  version: '1.0'
servers:
- url: https://api.onesourcetax.com/indirect-tax-determination/transaction-extracts/v1
  description: IDT US
- url: https://api-emea.onesourcetax.com/indirect-tax-determination/transaction-extracts/v1
  description: IDT EU
- url: https://api.onesourcetax.com/indirect-tax-determination-iv/transaction-extracts/v1
  description: IDT-IV US
- url: https://api-uat.onesourcetax.com/indirect-tax-determination/transaction-extracts/v1
  description: IDT US UAT
- url: https://api-uat.onesourcetax.com/indirect-tax-determination-iv/transaction-extracts/v1
  description: IDT-IV US UAT
paths:
  /indirect-tax-determination/transaction-extracts/v1/document-line-details/extract:
    post:
      tags:
      - report-controller
      description: Retrieve document line level details for a selected list of companies.
      operationId: extractTransactionsRequest
      parameters:
      - name: Authorization
        in: header
        description: JWT Authorization header using the Bearer scheme.
        required: true
        schema:
          type: string
        example: Bearer {token}
      - name: X-API-REQUEST-ID
        in: header
        description: Request ID
        schema:
          type: string
        example: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionExtractRequest'
        required: true
      responses:
        '200':
          description: Extract transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionExtractResponse'
            text/html:
              schema:
                $ref: '#/components/schemas/TransactionExtractResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/html:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: string
                example:
                  type: https://developers.onesourcetax.com/errors/#keymanagement.service.invalid_access_token
                  title: Invalid Access Token
                  detail: Invalid Access Token
                  status: 401
                  instance: /indirect-tax-determination/transaction-extracts/v1/document-line-details/extract
                  api_requestId: rrt-0dca53a2ef58eee6c-c-sa-15013-3687472-1
            text/html:
              schema:
                type: string
                example:
                  type: https://developers.onesourcetax.com/errors/#keymanagement.service.invalid_access_token
                  title: Invalid Access Token
                  detail: Invalid Access Token
                  status: 401
                  instance: /indirect-tax-determination/transaction-extracts/v1/document-line-details/extract
                  api_requestId: rrt-0dca53a2ef58eee6c-c-sa-15013-3687472-1
        '403':
          description: Forbidden access
          content:
            text/html:
              schema:
                type: string
                example: "<html>\n   <head>\n      <title>403 Forbidden</title>\n   </head>\n   <body>\n      <center>\n         <h1>403 Forbidden</h1>\n      </center>\n      <hr>\n      <center>nginx</center>\n   </body>\n</html>"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
                example:
                  type: https://developerportal.thomsonreuters.com/authorization-onesource-api
                  title: Resource Not Found
                  detail: Resource Not Found
                  status: 404
                  instance: /indirect-tax-determination/transaction-extracts/v1/document-line-details/extract1
                  api_requestId: rrt-0e0cd8ac8b651413c-d-ea-20265-16503786-1
            text/html:
              schema:
                type: string
                example:
                  type: https://developerportal.thomsonreuters.com/authorization-onesource-api
                  title: Resource Not Found
                  detail: Resource Not Found
                  status: 404
                  instance: /indirect-tax-determination/transaction-extracts/v1/document-line-details/extract1
                  api_requestId: rrt-0e0cd8ac8b651413c-d-ea-20265-16503786-1
        '500':
          description: Internal Server Error
          content:
            text/html:
              schema:
                type: string
                example: Internal server error. {"timestamp":"2023-09-06T12:07:30.472+00:00","status":500,"error":"Internal Server Error","path":"/indirect-tax-determination/transaction-extracts/v1/document-line-details/extract"}
  /indirect-tax-determination/transaction-extracts/v1/document-line-details/metadata:
    get:
      tags:
      - report-controller
      description: Retrieve document metadata used for building transaction extract request.
      operationId: getParameters
      parameters:
      - name: Authorization
        in: header
        description: JWT Authorization header using the Bearer scheme.
        required: true
        schema:
          type: string
        example: Bearer {token}
      - name: X-API-REQUEST-ID
        in: header
        description: Request ID
        allowEmptyValue: true
        schema:
          type: string
        example: 1
      responses:
        '200':
          description: List of parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParametersResponse'
            text/html:
              schema:
                $ref: '#/components/schemas/ParametersResponse'
        '400':
          description: Bad request
          content:
            text/html:
              schema:
                type: string
                example: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<HTML>\n\n<HEAD>\n\t<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n\t<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD>\n\n<BODY>\n\t<H1>400 ERROR</H1>\n\t<H2>The request could not be satisfied.</H2>\n\t<HR noshade size=\"1px\">\n\tBad request.\n\tWe can't connect to the server for this app or website at this time. There might be too much traffic or a\n\tconfiguration error. Try again later, or contact the app or website owner.\n\t<BR clear=\"all\">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n\t<BR clear=\"all\">\n\t<HR noshade size=\"1px\">\n\t<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: _XoFzMpxRNvfWGnaVL3lDesSXPm9rD8-k0LaE29nTVmcwHFQMoMYXA==\n</PRE>\n\t<ADDRESS>\n\t</ADDRESS>\n\
                  </BODY>\n\n</HTML>"
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: string
                example:
                  type: https://developers.onesourcetax.com/errors/#oauth.v2.invalidaccesstoken
                  title: Invalid access token
                  detail: Invalid access token
                  status: 401
                  instance: /indirect-tax-determination/transaction-extracts/v1/document-line-details/metadata
                  api_requestId: rrt-0ef9c4ea8db8b2314-d-ea-20131-17225668-1
            text/html:
              schema:
                type: string
                example:
                  type: https://developers.onesourcetax.com/errors/#oauth.v2.invalidaccesstoken
                  title: Invalid access token
                  detail: Invalid access token
                  status: 401
                  instance: /indirect-tax-determination/transaction-extracts/v1/document-line-details/metadata
                  api_requestId: rrt-0ef9c4ea8db8b2314-d-ea-20131-17225668-1
        '403':
          description: Forbidden access
          content:
            text/html:
              schema:
                type: string
                example: "<html>\n   <head>\n      <title>403 Forbidden</title>\n   </head>\n   <body>\n      <center>\n         <h1>403 Forbidden</h1>\n      </center>\n      <hr>\n      <center>nginx</center>\n   </body>\n</html>"
        '404':
          description: Not Found
          content:
            text/html:
              schema:
                type: string
                example:
                  type: https://developerportal.thomsonreuters.com/authorization-onesource-api
                  title: Resource Not Found
                  detail: Resource Not Found
                  status: 404
                  instance: /indirect-tax-determination/transaction-extracts/v1/document-line-details/metadata1
                  api_requestId: rrt-0aea4df2ad2926d77-b-sa-14899-3826497-1
        '500':
          description: Internal Server Error
          content:
            text/html:
              schema:
                type: string
                example: Internal server error. {"timestamp":"2023-09-06T12:07:30.472+00:00","status":500,"error":"Internal Server Error","path":"/indirect-tax-determination/transaction-extracts/v1/document-line-details/metadata"}
  /health-check:
    get:
      tags:
      - system-controller
      description: Health Check Message
      operationId: getHealthCheck
      responses:
        '200':
          description: Successfully retrieved
          content:
            application/json:
              schema:
                type: string
                example:
                  databaseConnectionHealthy: true
                  authorizationServiceHealthy: true
        '404':
          description: The resource you were trying to reach is not found
          content:
            application/json:
              schema:
                type: object
  /api-info:
    get:
      tags:
      - system-controller
      description: Get API Info
      operationId: getApiInfo
      responses:
        '200':
          description: Successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInfoResponse'
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: The resource you were trying to reach is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    AttributeFilter:
      type: object
      properties:
        name:
          type: string
          description: Custom attribute name
        operator:
          type: string
          description: 'This field accepts the following:

            eq - equal

            ne - not equal'
          enum:
          - eq
          - ne
        value:
          type: string
          description: The custom attribute value for which records needs compared and included.
      description: List of custom attribute predicates for which the transactions to be included in the response
    DateTypes:
      type: string
      description: "Identifies one of the following date types for transactions in the database:\n·Transaction - The date range is based on the date the taxcalculation occurs for the document. Format must be yyyy-mm-dd.\n·Document - The date range is based on document dates. Format must be yyyy-mm-dd. \n·Fiscal - The date range is based on fiscal dates indicated by each transaction. Format must be yyyy-mm-dd. \n·Creation - The timestamp range is based on creation date. Format must be yyyy-mm-dd hh:mm:ss.\n·Insert - The timestamp range is based on insert timestamp. Format must be yyyy-mm-dd hh:mm:ss."
      enum:
      - transaction
      - fiscal
      - document
      - creation
      - insert
    TransactionExtractRequest:
      required:
      - endDate
      - startDate
      type: object
      properties:
        companyNames:
          type: array
          description: Names of companies in the Determination database.
          items:
            type: string
            description: Names of companies in the Determination database.
        dateType:
          $ref: '#/components/schemas/DateTypes'
        startDate:
          type: string
          description: Start date for a given date range.
        endDate:
          type: string
          description: End date(inclusive) for a given date range.
        movementDateType:
          type: string
          description: Movement date type for with the date range is specified :[Movement Date,Movement Date - Line,Original Movement Date, Original Movement Date - Line]
          enum:
          - Movement Date
          - Movement Date - Line
          - Original Movement Date
          - Original Movement Date - Line
        movementStartDate:
          type: string
          description: Movement start date of date range for which the extract is being requested
        movementEndDate:
          type: string
          description: Movement end date of date range for which the extract is being requested
        taxableCountries:
          type: array
          description: Countries where selected companies have a tax obligation.
          items:
            type: string
            description: Countries where selected companies have a tax obligation.
        taxableStates:
          type: array
          description: States where the selected company or companies have tax obligations.
          items:
            type: string
            description: States where the selected company or companies have tax obligations.
        taxableProvinces:
          type: array
          description: Provinces where the selected company or companies have tax obligations.
          items:
            type: string
            description: Provinces where the selected company or companies have tax obligations.
        authorityTypes:
          type: array
          description: List of authority types for which the transactions to be included in the response
          items:
            type: string
            description: List of authority types for which the transactions to be included in the response
        transactionTypes:
          type: array
          description: 2-digit code based on the selected company(s) used in tax data.
          items:
            type: string
            description: 2-digit code based on the selected company(s) used in tax data.
        taxTypes:
          type: array
          description: 2-character abbreviation code used in tax data. Tax type is determined when the jurisdiction is determined. Some tax types are specific to only US or International transactions.
          items:
            type: string
            description: 2-character abbreviation code used in tax data. Tax type is determined when the jurisdiction is determined. Some tax types are specific to only US or International transactions.
        authorityNames:
          type: array
          description: List of tax authority names for which the transactions to be included in the response
          items:
            type: string
            description: List of tax authority names for which the transactions to be included in the response
        productCodes:
          type: array
          description: ERP system product codes.
          items:
            type: string
            description: ERP system product codes.
        companyRoles:
          type: array
          description: The role the company plays in a given transaction:Buyer,Seller,or Middleman. Also seen in Determination as Merchant role.
          items:
            type: string
            description: The role the company plays in a given transaction:Buyer,Seller,or Middleman. Also seen in Determination as Merchant role.
        taxDirection:
          type: string
          description: 'Specifies direction in which taxes are paid:

            ·Empty String (Any)

            ·I (Input Tax)

            ·O (Output Tax)'
        commodityCodes:
          type: array
          description: Commodity identifier for a transaction.
          items:
            type: string
            description: Commodity identifier for a transaction.
        customerNumbers:
          type: array
          description: An optional customer number(s) to limit output.
          items:
            type: string
            description: An optional customer number(s) to limit output.
        documentNumbers:
          type: array
          description: List of document numbers, document number is a transaction identifier;for example,an invoice or credit memo number.
          items:
            type: string
            description: List of document numbers, document number is a transaction identifier;for example,an invoice or credit memo number.
        vendorNumbers:
          type: array
          description: Comes from Determination data source.
          items:
            type: string
            description: Comes from Determination data source.
        fields:
          type: array
          description: List of column name (header).
          items:
            type: string
            description: List of column name (header).
        attributeFilters:
          type: array
          description: List of custom attribute predicates for which the transactions to be included in the response
          items:
            $ref: '#/components/schemas/AttributeFilter'
        excludeFullyExemptTransactions:
          type: boolean
          description: '"True" omits fully exempt tax lines."False"includes fully exempt tax lines.'
        vctAppliedFlag:
          type: boolean
          description: '"True" VCT applied "False"VCT not applied'
        offset:
          minimum: 0
          type: integer
          description: Offset of paginated response
          format: int32
        limit:
          minimum: 1
          type: integer
          description: Limit of records per page of response
          format: int32
      description: Extract Transactions Request
    MetaData:
      required:
      - fields
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
        totalItems:
          type: integer
          format: int32
      description: The wrapper for transaction extract response to contain metadata like column/fields, total no. of records in the response etc.
    TransactionExtractResponse:
      required:
      - items
      type: object
      properties:
        items:
          type: array
          description: The list of records in transaction extract response.
          items:
            type: object
            description: The list of records in transaction extract response.
        get_meta:
          $ref: '#/components/schemas/MetaData'
      example:
        items:
        - - NGRA_Cloud_QA_TestCompany
          - BuyerAudit21-017-2020 09170009:17:00+0000
          - 19821899
        - - NGRA_Cloud_QA_TestCompany
          - BuyerAudit21-040-2020 08404508:40:45+0000
          - 19579836
        _meta:
          fields:
          - Company Name
          - Document Number
          - Internal Invoice ID
          totalItems: 2
    Error:
      type: object
      properties:
        code:
          type: string
          description: HTTP error code
        message:
          type: string
          description: Error message
        details:
          type: array
          description: List to include the detail of error message, root cause or possible resolution.
          items:
            type: string
            description: List to include the detail of error message, root cause or possible resolution.
    ErrorResponse:
      required:
      - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/Error'
      example:
        error:
          code: 400 BAD_REQUEST
          message: 'Unrecognized token ''asd'': was expecting (JSON String, Number, Array, Object or token ''null'', ''true'' or ''false'')'
          details:
          - "com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'asd': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 4, column: 31]"
    Company:
      type: object
      properties:
        companyName:
          type: string
          description: Name of the company used is authorized
        countries:
          type: array
          description: 'List of countries with transaction for the company '
          items:
            $ref: '#/components/schemas/Country'
        taxTypes:
          type: array
          description: List of tax types with transaction for the company
          items:
            type: string
            description: List of tax types with transaction for the company
        transactionTypes:
          type: array
          description: List of transaction types with transaction for the company
          items:
            type: string
            description: List of transaction types with transaction for the company
        authorityTypes:
          type: array
          description: List of authority types with transaction for the company
          items:
            type: string
            description: List of authority types with transaction for the company
      description: List of companies the user is authorized to access.
    Country:
      type: object
      properties:
        taxableCountry:
          type: string
        taxableStates:
          type: array
          items:
            type: string
        taxableProvinces:
          type: array
          items:
            type: string
      description: 'List of countries with transaction for the company '
    FieldGroupInfo:
      type: object
      properties:
        fieldGroup:
          type: string
        fieldInfos:
          type: array
          items:
            $ref: '#/components/schemas/FieldInfo'
      description: Mapping of field/column group name and associated fields
    FieldInfo:
      type: object
      properties:
        field:
          type: string
    ParametersResponse:
      type: object
      properties:
        companies:
          type: array
          description: List of companies the user is authorized to access.
          items:
            $ref: '#/components/schemas/Company'
        companyRoles:
          type: array
          description: List of companies roles the user is authorized for.
          items:
            type: string
            description: List of companies roles the user is authorized for.
        fieldGroupInfos:
          type: array
          description: Mapping of field/column group name and associated fields
          items:
            $ref: '#/components/schemas/FieldGroupInfo'
      example:
        companies:
        - companyName: NGRA_Cloud_QA_TestCompany
          countries:
          - taxableCountry: UNITED STATES
            taxableStates:
            - SOUTH CAROLINA
            taxableProvinces:
            - N/A
          taxTypes:
          - Sales
          - Use
          - No Liability
          - European Community Dispatch
          - Consumer Use
          transactionTypes:
          - Goods
          authorityTypes:
          - District Sales/Use
          - County Sales/Use
          - State Sales/Use
          - City Sales/Use
          - TVA
          - Business and Occupation
        companyRoles:
        - B
        - S
        - M
        fieldGroupInfos:
        - fieldGroup: Addresses - Document
          fieldInfos:
          - field: Bill To Facility ID
          - field: Middleman District
        - fieldGroup: Tax Code Qualification
          fieldInfos:
          - field: ERP Tax Code
    ApiInfoResponse:
      type: object
      properties:
        version:
          type: string
        authorizationHost:
          type: string
        dataSourceUrl:
          type: string
      example:
        version: 1.16.0.
        authorizationHost: onesource-idt-det-sandbox-int.hostedtax.thomsonreuters.com
        dataSourceUrl: a206447-deal-query-service-use1-dev.tr-tax-nonprod.aws-int.thomsonreuters.com:5439/deal_dev
  securitySchemes:
    JWT:
      type: apiKey
      name: Authorization
      in: header
